// Package bootstrap provides repo scanning and discovery for gt rig bootstrap.
package bootstrap

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/steveyegge/gastown/internal/harness"
)

// GenerateOptions controls generation behavior.
type GenerateOptions struct {
	// DryRun shows what would be generated without writing.
	DryRun bool
}

// GenerateResult summarizes what was generated.
type GenerateResult struct {
	AgentsMDPath     string // path written (empty if skipped)
	AgentsMDAction   string // "created", "updated", "skipped"
	CodebaseMapPath  string
	CodebaseMapAction string // "created", "skipped"
}

// discoveredSection is the marker for the auto-generated section in AGENTS.md.
const discoveredSection = "## Discovered"

// GenerateAgentsMD generates or updates AGENTS.md with pointers to discovered docs.
// If AGENTS.md exists, appends/replaces the "## Discovered" section without
// overwriting manual content above it.
func GenerateAgentsMD(repoRoot string, manifest *Manifest, cmds harness.Commands, opts GenerateOptions) (*GenerateResult, error) {
	result := &GenerateResult{}
	agentsPath := filepath.Join(repoRoot, "AGENTS.md")
	result.AgentsMDPath = agentsPath

	section := buildDiscoveredSection(manifest, cmds)

	existing, err := os.ReadFile(agentsPath) //nolint:gosec // G304: trusted repo path
	if err == nil {
		// File exists — merge by replacing/appending the Discovered section.
		updated := mergeDiscoveredSection(string(existing), section)
		if updated == string(existing) {
			result.AgentsMDAction = "skipped"
			return result, nil
		}
		result.AgentsMDAction = "updated"
		if !opts.DryRun {
			if err := os.WriteFile(agentsPath, []byte(updated), 0644); err != nil { //nolint:gosec
				return nil, fmt.Errorf("writing AGENTS.md: %w", err)
			}
		}
		return result, nil
	}

	// No existing file — generate from scratch.
	content := buildFullAgentsMD(manifest, cmds)
	result.AgentsMDAction = "created"
	if !opts.DryRun {
		if err := os.WriteFile(agentsPath, []byte(content), 0644); err != nil { //nolint:gosec
			return nil, fmt.Errorf("writing AGENTS.md: %w", err)
		}
	}
	return result, nil
}

// GenerateCodebaseMap generates CODEBASE_MAP.md from directory scanning.
// Skipped if an architecture doc already exists in the manifest.
func GenerateCodebaseMap(repoRoot string, manifest *Manifest, opts GenerateOptions) (*GenerateResult, error) {
	result := &GenerateResult{}
	mapPath := filepath.Join(repoRoot, "CODEBASE_MAP.md")
	result.CodebaseMapPath = mapPath

	// Skip if architecture doc exists.
	if hasArchitectureDoc(manifest) {
		result.CodebaseMapAction = "skipped"
		return result, nil
	}

	// Skip if CODEBASE_MAP.md already exists.
	if _, err := os.Stat(mapPath); err == nil {
		result.CodebaseMapAction = "skipped"
		return result, nil
	}

	content, err := buildCodebaseMap(repoRoot, manifest)
	if err != nil {
		return nil, fmt.Errorf("building codebase map: %w", err)
	}

	result.CodebaseMapAction = "created"
	if !opts.DryRun {
		if err := os.WriteFile(mapPath, []byte(content), 0644); err != nil { //nolint:gosec
			return nil, fmt.Errorf("writing CODEBASE_MAP.md: %w", err)
		}
	}
	return result, nil
}

// --- AGENTS.md generation ---

func buildFullAgentsMD(manifest *Manifest, cmds harness.Commands) string {
	var b strings.Builder
	b.WriteString("# Agent Instructions\n\n")
	b.WriteString("See **GT.md** for Gas Town operational guidelines.\n\n")
	b.WriteString(buildDiscoveredSection(manifest, cmds))
	return b.String()
}

func buildDiscoveredSection(manifest *Manifest, cmds harness.Commands) string {
	var b strings.Builder
	b.WriteString(discoveredSection + "\n\n")
	b.WriteString("*Auto-generated by `gt rig bootstrap`. Do not edit above this section.*\n\n")

	// Project docs
	docs := artifactsByType(manifest, TypeDoc)
	if len(docs) > 0 {
		b.WriteString("### Documentation\n\n")
		for _, d := range docs {
			b.WriteString(fmt.Sprintf("- [%s](%s) — %s\n", d.Name, d.Path, d.Detail))
		}
		b.WriteString("\n")
	}

	// Coding standards (lint + format configs)
	lints := artifactsByType(manifest, TypeLintConfig)
	fmts := artifactsByType(manifest, TypeFmtConfig)
	if len(lints) > 0 || len(fmts) > 0 {
		b.WriteString("### Coding Standards\n\n")
		for _, a := range lints {
			b.WriteString(fmt.Sprintf("- Lint: %s (%s)\n", a.Path, a.Detail))
		}
		for _, a := range fmts {
			b.WriteString(fmt.Sprintf("- Format: %s (%s)\n", a.Path, a.Detail))
		}
		if hasType(manifest, TypeEditorCfg) {
			b.WriteString("- Editor: .editorconfig\n")
		}
		if hasType(manifest, TypeTSConfig) {
			b.WriteString("- TypeScript: tsconfig.json\n")
		}
		b.WriteString("\n")
	}

	// Testing
	testCfgs := artifactsByType(manifest, TypeTestConfig)
	testDirs := artifactsByType(manifest, TypeTestDir)
	if len(testCfgs) > 0 || len(testDirs) > 0 {
		b.WriteString("### Testing\n\n")
		for _, a := range testCfgs {
			b.WriteString(fmt.Sprintf("- Framework: %s (%s)\n", a.Detail, a.Path))
		}
		for _, a := range testDirs {
			b.WriteString(fmt.Sprintf("- Directory: %s/\n", a.Path))
		}
		if cmds.Test != "" {
			b.WriteString(fmt.Sprintf("- Run: `%s`\n", cmds.Test))
		}
		b.WriteString("\n")
	}

	// Verification commands
	if cmds.Build != "" || cmds.Test != "" || cmds.Lint != "" || cmds.Typecheck != "" {
		b.WriteString("### Verification\n\n")
		b.WriteString("Before submitting work, these must pass:\n\n")
		if cmds.Build != "" {
			b.WriteString(fmt.Sprintf("- `%s` (tier0)\n", cmds.Build))
		}
		if cmds.Test != "" {
			b.WriteString(fmt.Sprintf("- `%s` (tier0)\n", cmds.Test))
		}
		if cmds.Lint != "" {
			b.WriteString(fmt.Sprintf("- `%s` (tier1)\n", cmds.Lint))
		}
		if cmds.Typecheck != "" {
			b.WriteString(fmt.Sprintf("- `%s` (tier1)\n", cmds.Typecheck))
		}
		b.WriteString("\n")
	}

	return b.String()
}

// mergeDiscoveredSection replaces the "## Discovered" section in existing content,
// or appends it if not present. Preserves all content above the section.
func mergeDiscoveredSection(existing, newSection string) string {
	idx := strings.Index(existing, discoveredSection)
	if idx >= 0 {
		// Replace from "## Discovered" to end of file.
		return existing[:idx] + newSection
	}
	// Append with separator.
	s := strings.TrimRight(existing, "\n") + "\n\n" + newSection
	return s
}

// --- CODEBASE_MAP.md generation ---

// dirEntry represents a directory in the tree.
type dirEntry struct {
	Name     string
	Path     string // relative to repo root
	FileCount int
}

func buildCodebaseMap(repoRoot string, manifest *Manifest) (string, error) {
	var b strings.Builder
	b.WriteString("# Codebase Map\n\n")

	// Structure section
	dirs, err := scanTopDirs(repoRoot)
	if err != nil {
		return "", err
	}
	if len(dirs) > 0 {
		b.WriteString("## Structure\n\n")
		b.WriteString("```\n")
		for _, d := range dirs {
			if d.FileCount > 0 {
				b.WriteString(fmt.Sprintf("%-15s (%d files)\n", d.Name+"/", d.FileCount))
			} else {
				b.WriteString(d.Name + "/\n")
			}
		}
		b.WriteString("```\n\n")
	}

	// Entry points
	entries := findEntryPoints(repoRoot, manifest)
	if len(entries) > 0 {
		b.WriteString("## Entry Points\n\n")
		for _, e := range entries {
			b.WriteString(fmt.Sprintf("- %s\n", e))
		}
		b.WriteString("\n")
	}

	// Dependencies
	deps := readDependencies(repoRoot, manifest)
	if len(deps) > 0 {
		b.WriteString("## Dependencies\n\n")
		for _, d := range deps {
			b.WriteString(fmt.Sprintf("- %s\n", d))
		}
		b.WriteString("\n")
	}

	return b.String(), nil
}

// scanTopDirs returns top-level directories, excluding hidden/vendor/build dirs.
func scanTopDirs(root string) ([]dirEntry, error) {
	entries, err := os.ReadDir(root)
	if err != nil {
		return nil, err
	}

	skipDirs := map[string]bool{
		"node_modules": true, "vendor": true, ".git": true,
		".github": true, ".gastown": true, ".beads": true,
		"dist": true, "build": true, "__pycache__": true,
		"target": true, ".idea": true, ".vscode": true,
	}

	var dirs []dirEntry
	for _, e := range entries {
		if !e.IsDir() {
			continue
		}
		name := e.Name()
		if strings.HasPrefix(name, ".") && name != ".github" {
			continue
		}
		if skipDirs[name] {
			continue
		}
		count := countFiles(filepath.Join(root, name))
		dirs = append(dirs, dirEntry{Name: name, Path: name, FileCount: count})
	}
	sort.Slice(dirs, func(i, j int) bool { return dirs[i].Name < dirs[j].Name })
	return dirs, nil
}

// countFiles counts non-directory entries one level deep.
func countFiles(dir string) int {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return 0
	}
	count := 0
	for _, e := range entries {
		if !e.IsDir() {
			count++
		}
	}
	return count
}

// findEntryPoints looks for common entry point files.
func findEntryPoints(root string, manifest *Manifest) []string {
	candidates := []string{
		"main.go", "cmd/main.go",
		"src/index.ts", "src/index.js", "src/main.ts", "src/main.js",
		"index.ts", "index.js",
		"src/main.py", "main.py", "app.py",
		"src/main.rs", "src/lib.rs",
	}
	var found []string
	for _, c := range candidates {
		if _, err := os.Stat(filepath.Join(root, c)); err == nil {
			found = append(found, c)
		}
	}
	// Check cmd/ subdirectories for Go projects.
	if hasArtifact(manifest, TypeBuildFile, "go.mod") {
		cmdDir := filepath.Join(root, "cmd")
		if entries, err := os.ReadDir(cmdDir); err == nil {
			for _, e := range entries {
				if e.IsDir() {
					main := filepath.Join("cmd", e.Name(), "main.go")
					if _, err := os.Stat(filepath.Join(root, main)); err == nil {
						found = append(found, main)
					}
				}
			}
		}
	}
	return found
}

// readDependencies extracts top-level dependency names from go.mod or package.json.
func readDependencies(root string, manifest *Manifest) []string {
	if hasArtifact(manifest, TypeBuildFile, "go.mod") {
		return readGoModDeps(filepath.Join(root, "go.mod"))
	}
	if hasArtifact(manifest, TypeBuildFile, "package.json") {
		return readPackageJSONDeps(filepath.Join(root, "package.json"))
	}
	return nil
}

func readGoModDeps(path string) []string {
	data, err := os.ReadFile(path) //nolint:gosec
	if err != nil {
		return nil
	}
	var deps []string
	inRequire := false
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "require (" {
			inRequire = true
			continue
		}
		if line == ")" {
			inRequire = false
			continue
		}
		if inRequire && line != "" && !strings.HasPrefix(line, "//") {
			parts := strings.Fields(line)
			if len(parts) >= 1 {
				// Use short module name.
				mod := parts[0]
				if idx := strings.LastIndex(mod, "/"); idx >= 0 {
					mod = mod[idx+1:]
				}
				deps = append(deps, mod)
			}
		}
	}
	if len(deps) > 20 {
		deps = deps[:20]
	}
	return deps
}

func readPackageJSONDeps(path string) []string {
	data, err := os.ReadFile(path) //nolint:gosec
	if err != nil {
		return nil
	}
	var pkg struct {
		Dependencies    map[string]string `json:"dependencies"`
		DevDependencies map[string]string `json:"devDependencies"`
	}
	if err := json.Unmarshal(data, &pkg); err != nil {
		return nil
	}
	var deps []string
	for k := range pkg.Dependencies {
		deps = append(deps, k)
	}
	sort.Strings(deps)
	if len(deps) > 20 {
		deps = deps[:20]
	}
	return deps
}

// --- helpers ---

func artifactsByType(m *Manifest, t ArtifactType) []Artifact {
	var out []Artifact
	for _, a := range m.Artifacts {
		if a.Type == t {
			out = append(out, a)
		}
	}
	return out
}

func hasType(m *Manifest, t ArtifactType) bool {
	for _, a := range m.Artifacts {
		if a.Type == t {
			return true
		}
	}
	return false
}

func hasArtifact(m *Manifest, t ArtifactType, name string) bool {
	for _, a := range m.Artifacts {
		if a.Type == t && a.Name == name {
			return true
		}
	}
	return false
}

func hasArchitectureDoc(m *Manifest) bool {
	for _, a := range m.Artifacts {
		if a.Type == TypeDoc && a.Name == "ARCHITECTURE" {
			return true
		}
	}
	return false
}
